branches:
  only:
  - travistest
  - latest-release
sudo: required
services: docker
script:
  - docker pull strauman/travis-latexbuild
  - docker run --mount src=$TRAVIS_BUILD_DIR/tests,target=/src,type=bind --mount src=$TRAVIS_BUILD_DIR/src,target=/src/src,type=bind strauman/travis-latexbuild
