## Create quickstart
cd $sourceDir
# rm quickstart.zip
# zip quickstart.zip example.tex $outfile -r ../exercises


# Create CTAN zip
rm -rf exercisebank
mkdir exercisebank

zip example.zip example.tex -r ../exercises

cp ../docs/exercisebank-doc.pdf exercisebank/
cp ../docs/exercisebank-doc.tex exercisebank/
cp example.zip exercisebank/
cp README.txt exercisebank/
cp $tmpDir/$outfile exercisebank/

zip exbankCTAN.zip -r exercisebank/
mv exbankCTAN.zip ../
# rm -rf exercisebank/

rm ../example.tex
cp example.tex ../

rm ../$outfile
cp $tmpDir/$outfile ../

cp ../$outfile /Users/Andreas/Documents/uit/fag/TA/FYS-1002/Oppgaver\ FYS-1002/$outfile
mv example.zip ../

rm -rf ../exercisebank/
mv exercisebank/ ../
mv ../README.md ../README.md.bak
echo -e "<!---\n DO NOT EDIT THIS FILE \n EDITS SHOULD BE DONE IN src/README.md.template \n-->" > ../README.md
cat README.md.template >> ../README.md
cd ../
outHandle "Error when inserting package-variables to README.md-file" $perlDir/vars.pl -v $version -p $packagename -g $github -b $build README.md
# git tag "v${version}b$build"
echo "Tag at v${version}b$build"
