## Create quickstart
cd $sourceDir
# rm quickstart.zip
# zip quickstart.zip example.tex $outfile -r ../exercises


# Copy docs
cp ../docs/exercisebank-doc.pdf exercisebank/
cp ../docs/exercisebank-doc.tex exercisebank/
# Create example zip
## Build example
rm ../example.tex
cp example.tex ../
cd $mainDir
latexmk -pdf ../example.tex -f -outdir=bin
mv bin/example.pdf $sourceDir/example.pdf
cd $sourceDir
# Zip example
zip example.zip example.tex -r ../exercises example.pdf
# Cleanup
mv example.pdf ../

# Create CTAN zip
rm -rf exercisebank
mkdir exercisebank
cp example.zip exercisebank/
cp README.txt exercisebank/
cp $tmpDir/$outfile exercisebank/
cd exercisebank/
outHandle "Error when inserting package-variables to README.txt-file" $perlDir/vars.pl -v $version -p $packagename -g $github -b $build README.txt
cd ../
cp $docOutDir/$docOutFileBaseName.tex exercisebank/
cp $docOutDir/$docOutFileBaseName.pdf exercisebank/
zip exbankCTAN.zip -r exercisebank/
rm ../exbankCTAN.zip
mv exbankCTAN.zip ../

# Cleanup
# Update .sty
rm ../$outfile
cp $tmpDir/$outfile ../

# Copy .sty to live project
cp ../$outfile /Users/Andreas/Documents/uit/fag/TA/FYS-1002/Oppgaver\ FYS-1002/$outfile
# Copy example zip to root
rm ../example.zip
mv example.zip ../
# Copy exercisebank dir to root
rm -rf ../exercisebank
mv exercisebank/ ../
# Get github README ready
mv ../README.md ../README.md.bak
echo -e "<!---\n DO NOT EDIT THIS FILE \n EDITS SHOULD BE DONE IN src/README.template.md \n-->" > ../README.md
cat README.template.md >> ../README.md
cd ../
outHandle "Error when inserting package-variables to README.md-file" $perlDir/vars.pl -v $version -p $packagename -g $github -b $build README.md
# git tag "v${version}b$build"
echo "Tag at v${version}b$build"
